server:
  port: ${SERVER_PORT:8082}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  application:
    name: tecrubesi-user
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres?currentSchema=neutar_user
    username: postgres
    password: 123456
  flyway:
    schemas: neutar_user
  kafka:
    listener:
      missing-topics-fatal: false
security:
  oauth2:
    resource:
      jwt:
        key-value: neutar
kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost}:9092
  groupId: neutar_user
