server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres?currentSchema=neutar_user
    username: postgres
    password: 123456
  flyway:
    schemas: neutar_user
