version: '3'
services:
  portainer:
    image: "portainer/portainer:latest"
    ports:
      - 9000:9000
    volumes:
      - "${PORTAINER_DATA_PATH:-/portainerdata}:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"